sudo: false
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"

language: scala
scala:
- 2.11.8

script:
- "sbt test it:test unidoc"

jdk:
- oraclejdk8

notifications:
  email:
    on_success: never
    on_failure: change
