sudo: false
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"

language: scala
scala:
- 2.11.8

script:
- "sbt test it:test unidoc"
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then sbt
  "gitPublish target/javaunidoc https://$GH_TOKEN:x-oauth-basic@github.com/$TRAVIS_REPO_SLUG.git
  javadoc sphere-oss automation@commercetools.de"; fi\

jdk:
- oraclejdk8

notifications:
  email:
    on_success: never
    on_failure: change

env:
  global:
  - secure: nGG3PB1huVj+7CFGq/qMU3pz+zMX48aSk7Eg9DZ8K3YD4xxm0HQYjGIaQi4H9XC+e0WBwcWBWxzWSjdfyhaIWHaK5bc4Cfkw6teYmjaE/CvFG18m33uAFPn0yR72w19w9A2wMZovDO1Aq0i7TlilHl4oZ0CErUA/J0yPh69DPM7to96mEfHGyXqclKTl727Lwp1cg/KGyQT9DS9tfxgzOHbBJ8R88j9tH5ZHyQMV/uuDm9z422JdwlN6InJero7DR2HAy3rInkNq42cupnd6DkovvqVl1gKWEd8ONudmwGTTJxQEtYfQPc8jincqn0xLhEcb/RuBjJ0PG1K1DUKT5BJzPI8IJ48VIRRxj1SGsA/9lz1BNVcJdkm48FzIhEJg7XbHvV5FblqfDF9CnIiANAE5NUfW/9ourLtXYyyqlk3LY/EjvnZ7iw4yyahGO7/38o+e+1Z6mkTpC/yz7WAs7GB/E+qUgZELblLftEFCLfah+GB8dfP/whdt/V3urulW5U7fUaLm6LOCUo0iAnWHeipvrZqpMTPn/NeSxfxHFnckTse+timAnRRMxbasR2iw+YUT+5SBG5aqqawVFdkrVg/KHS1ceeMiV/QxP46MWKMJQ2qmwKvQ3GHr0VRpyPO/gMwGHsLsm0SrfZybwKF5ckqeLQDzuYve6V2YGkLMa08=
  - secure: I7p48/8UMoQqiZ2xsmxrhGYgfIVBPw3a5Hmv9B2nZJOt/MvPmEutoYrB5NGM+t9PlQM9EfosGZ5rGimRcyUJRtDicT0xGsDj/2yAipub6MLBqLM1UZrl8KRa47boXmp+VOgD5ofL0NrERoA/NtTduRUF8tGDMbe7kT9NtQ1er62p9KPMMEAs63fywSw+1DL7D9CqrLFaNxmICPZuU7DLPTiD5k82p+olW5WFPkyaWQ6cMWf0Wvtz24Adziwj5mE2WIPZrDZa4VQiTbk9a1c2k7KUbMq21VaxZDVDWixYRt2BR5SXuM199GlcXE00vgOra0uP+llsqyxuIr7L3qoidFLQAPh9CFOqppC7iHaKDga3FHsLCS8VgTbrLur99c4fUB220BmgivbRCglGI3G7lxsuCIuKXcuNz6qMz1wlOvDOGGiptyJE6qtXJG+9T5EWaPe1c3dqDkx4o0ZKVGbSsedUfS6CX295m+E1cVkdupRKXvL6zUXXQtTCzNkt/mjTCEDkQaY+KllBpdU3z4qbEkZc1wYjsEs2D731jfqKQl0M7Xrzw9GSjyfpSkiXg7QuEhGT5kmxrDCfc7sv2/rcF7RdGHSZPkK/jdvlT4buFBDI+zVZgm6dcjah6Z3EDgrgbBgBVPrmAMuWrxaCyjvxc53qBwpRFWkVtCHXcPjsO1I=
