sudo: false
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"

language: scala
scala:
- 2.11.8

script:
- "sbt test it:test unidoc"
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then sbt
  "gitPublish target/javaunidoc https://$GH_TOKEN:x-oauth-basic@github.com/$TRAVIS_REPO_SLUG.git
  javadoc sphere-oss automation@commercetools.de"; fi\

jdk:
- oraclejdk8

notifications:
  email:
    on_success: never
    on_failure: change

env:
  global:
  - secure: Crv7LEY/vXTEyeXqbzKs4vffVHKYg6oRUc+scodOLihdq///YHSB1hgY980nCF2S2SEnCDvb62JLqR4Tee4a4KHHsawfrjM+2ezLc2ZKhNMAEEMpVDCD8DhVn4AxKDGvvpOXbL7If1GofFtQxRajNOv46yyr4TEcw2SdVrBVMP4mgFwokGOpzVYL8WoWtwcBNSzeMRs8GoJESd3OD/ZERHvY1HiC0DKa3cAmTvX/Kfb+NEYf7831BX3Jt5eknwC+yNERWC+ue8Oilm3qBdJx7u68YZMT0hZVajUTol01SPUQ9DOFlDZdP/Nc3uSRUdOlQx/uxi+RDgPlzRDz6KyH1vhDa6HczOmvg5HKhV683Tt32YjHbLQv35f6K3ASpgiliClhAgXm1x4i78xp/HTOwq5hbHHHHKuxJ+kUzoIqz0KkN/69ztvJWhyAqgN3dysV0Clcv/W6No3ABlNO5F7VoGBZ5m+IknPadzwel7a9U843wxYLQM/Or6KMvXW7MRYO+rlhkWjO+MBNdQti2F0gGIv65ZZ111uosZ7QSvajGwqq0q5bJK671drRZHX1kk4t63cA1HffNCLc3IGAd6wvPkuyzzKSd0xjgtskvURC1hwB4mpijimefdyR/pWe6/CWLHW5FAhMCFq21Cv3mR6iqQqaB7dEE6h+oxQ/auhCvEE=
  - secure: EROmqSe5vmiuIc27xwRosUFtOPEmdH6i/zBEaUXCOuMsskKeub7AM0LOSHkj+Xp/0l1SSC/kDree44NJgtJTkhdDxFY+In4kpnX5x3qGD9qunkYfMb+3tJkCG8DGrLb7VKyiboHuCvmRUXSTM7SzkpaZ6HE937U1698Lv64pVFLyOTy3QzVPe91TxtPxg+0qCb4nrZb9N02ywWIOdktNgRPGv4LwQGHbq3KburAzpxepz9cgnAjNdQeMYHUzyPKeaiJ3J9FlRZuGovjwt2YQ0gn5iOQo7iwX4mZbQnMqhV6uoH8pHIPB0eEv1iTiu12jS5RGySd35pucI/B4/T+J4+CAtFgZA2gJuvDynhwyN770sSMcunKjI1I2U1hcaLI2JC2TnnxKDCGIQwcAnpOSzdo7Mtl960TiTk4oIQgUkOpyvVI3OS+4hg/nF8+O4GZPtNAwHFTkPuId34chd0p/JshQSSufJH2Dq/TjONuRKY6JEdjdAyBxsb7GlhN6TUAzgDuFPcxoO4AZqsKB6rmuPhmqSX474TcPKue5UgOVKXKYMzdb9zTe6zWpOtwV8kSBO6pB3B1EMAO+Zn+W1vO6il6yL/2m9IhVveSaqsqXRHP4Vi55jH0uur0zjNjqMCFNPGlSNYkqne/HVpWCrTIl/wJCP2fh8W3yppd4WTUptpM=
